name: Commit test (experiment)

on:
  workflow_dispatch:
    inputs:
      what:
        description: "Line to be added into pom.xml"
        required: true
        type: string
        default: blablabla

permissions:
  contents: write
  pull-requests: read

jobs:
  line-add:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add the line
      run: |
        env | sort
        ls -la
        echo "<!-- A: ${{ inputs.what }} -->" >> pom.xml
    - name: commit and push
      run: |
        echo "machine github.com" > "$HOME/.netrc"
        echo "  login $GITHUB_ACTOR" >> "$HOME/.netrc"
        echo "  password ${{ github.token }}" >> "$HOME/.netrc"
        echo "machine api.github.com" >> "$HOME/.netrc"
        echo "  login ${{ github.actor }}" >> "$HOME/.netrc"
        echo "  password ${{ github.token }}" >> "$HOME/.netrc"
        cat "$HOME/.netrc"
        git config --global user.email "releasator@gmail.com"
        git config --global user.name "Releasator"
        ls -la
        git commit -am "B line added"
        git push
