# This workflow prepares package for publishing in Maven Central via the Sonatype Nexus OSS Repository - https://oss.sonatype.org

name: Release to Maven Central

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Save files for post-release step
      run: |
        env | sort
        mkdir -p "target/release-package/post-release"
        cp "pom.xml" "target/release-package/post-release/"
        echo "GIT_REVISION: $(git rev-parse HEAD)" > "target/release-package/build.properties"

    - name: Switch to release version
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo "RELEASE_VERSION=$RELEASE_VERSION"
        mvn versions:set -DnewVersion=$RELEASE_VERSION
        sed -i 's:<scm>:<scm><tag>vRELEASE_VERSION</scm>:' pom.xml
        echo "TAG: v$RELEASE_VERSION" >> "target/release-package/build.properties"
        echo "VERSION: $RELEASE_VERSION" >> "target/release-package/build.properties"

    - name: Build release artifacts
      run: mvn deploy -Prelease -DaltDeploymentRepository=local::default::file://$PWD/target/release-package/repository -DdeployAtEnd

    - name: Save files for pre-release step
      run: |
        mkdir -p "target/release-package/pre-release"
        cp "pom.xml" "target/release-package/pre-release/"

    - uses: actions/upload-artifact@v3
      with:
        name: "release-package"
        path: target/release-package
        if-no-files-found: error
